-- Core/N_Adjacency.lean
-- Full adjacency characterisation for conv(P_n): Theorems 4.18, 4.19, Chapter 4.
-- Pedigree Polytopes (Arthanari, Springer Nature 2023).
--
-- P adj Q ↔ G_R(P,Q) is connected
-- Corollary: conv(P_n) is a combinatorial polytope.

import MembershipProject.Core.N_Discords

namespace MembershipProject.Core

-- ============================================================================
-- SECTION 1: THE DISCORD GRAPH G_R
-- ============================================================================
-- G_R has vertex set = discords P Q.
-- Edge (q₁, q₂) ∈ G_R iff q₁ and q₂ are "welded":
-- some pedigree R in a convex combination uses a triple at q₁ that was
-- generated by the triple at q₂ (or vice versa).

-- Helper: convert index bound across equal-length lists.
-- Placed here (before welded) because welded uses it for Q's index bounds.
private lemma swap_idx {n : ℕ} (P Q : Pedigree n) (i : ℕ)
    (hi : i < P.triangles.length) : i < Q.triangles.length := by
  rw [Q.h_length, ← P.h_length]; exact hi

-- Key structural lemma: g ∈ generators(t) with g.k ≥ 4 implies g.k = t.j.
-- Uses mem_generators_Delta (from N_RestrictionFull) + mem_Delta_k.
-- When t.j ≤ 3: generators(t) = {(1,2,3)}, g.k = 3 < 4 — contradicts hk4.
-- When t.j > 3: generators(t) ⊆ Delta(t.j), so g.k = t.j.
private lemma generators_layer {t g : Triple}
    (ht_i : 1 ≤ t.i) (ht_ij : t.i < t.j)
    (h : g ∈ generators t) (hk4 : g.k ≥ 4) : g.k = t.j := by
  have hmem := mem_generators_Delta ht_i ht_ij h
  have htj4 : t.j > 3 := by
    by_contra htj; push_neg at htj
    exact absurd (mem_Delta_k (by rwa [if_neg (by omega)] at hmem)) (by omega)
  rw [if_pos htj4] at hmem
  exact mem_Delta_k hmem

/-- Two discord positions q₁, q₂ are welded if the generator relationship holds
    in either direction, for P or Q. G_R is undirected so both directions count. -/
def welded {n : ℕ} (P Q : Pedigree n) (q₁ q₂ : ℕ) : Prop :=
  q₁ ∈ discords P Q ∧ q₂ ∈ discords P Q ∧ q₁ ≠ q₂ ∧
  ∃ (hq1 : q₁ - 3 < P.triangles.length) (hq2 : q₂ - 3 < P.triangles.length),
    -- P generators (both directions — G_R is undirected)
    P.triangles.get ⟨q₂-3, hq2⟩ ∈ generators (P.triangles.get ⟨q₁-3, hq1⟩)
    ∨ P.triangles.get ⟨q₁-3, hq1⟩ ∈ generators (P.triangles.get ⟨q₂-3, hq2⟩)
    -- Q generators (both directions)
    ∨ Q.triangles.get ⟨q₂-3, swap_idx P Q (q₂-3) hq2⟩ ∈
        generators (Q.triangles.get ⟨q₁-3, swap_idx P Q (q₁-3) hq1⟩)
    ∨ Q.triangles.get ⟨q₁-3, swap_idx P Q (q₁-3) hq1⟩ ∈
        generators (Q.triangles.get ⟨q₂-3, swap_idx P Q (q₂-3) hq2⟩)

-- Decidable instance: case-split on all four disjuncts.
instance {n : ℕ} (P Q : Pedigree n) (q₁ q₂ : ℕ) : Decidable (welded P Q q₁ q₂) :=
  if h1 : q₁ ∈ discords P Q then
  if h2 : q₂ ∈ discords P Q then
  if h3 : q₁ ≠ q₂ then
  if h4 : q₁ - 3 < P.triangles.length then
  if h5 : q₂ - 3 < P.triangles.length then
  if h6 :
    P.triangles.get ⟨q₂-3, h5⟩ ∈ generators (P.triangles.get ⟨q₁-3, h4⟩)
    ∨ P.triangles.get ⟨q₁-3, h4⟩ ∈ generators (P.triangles.get ⟨q₂-3, h5⟩)
    ∨ Q.triangles.get ⟨q₂-3, swap_idx P Q (q₂-3) h5⟩ ∈
        generators (Q.triangles.get ⟨q₁-3, swap_idx P Q (q₁-3) h4⟩)
    ∨ Q.triangles.get ⟨q₁-3, swap_idx P Q (q₁-3) h4⟩ ∈
        generators (Q.triangles.get ⟨q₂-3, swap_idx P Q (q₂-3) h5⟩) then
    isTrue ⟨h1, h2, h3, h4, h5, h6⟩
  else
    isFalse fun ⟨_, _, _, hq1, hq2, hmem⟩ => h6 (by
      have eP1 : P.triangles.get ⟨q₁-3, hq1⟩ = P.triangles.get ⟨q₁-3, h4⟩ :=
        congr_arg P.triangles.get (Fin.ext rfl)
      have eP2 : P.triangles.get ⟨q₂-3, hq2⟩ = P.triangles.get ⟨q₂-3, h5⟩ :=
        congr_arg P.triangles.get (Fin.ext rfl)
      have eQ1 : Q.triangles.get ⟨q₁-3, swap_idx P Q (q₁-3) hq1⟩ =
                 Q.triangles.get ⟨q₁-3, swap_idx P Q (q₁-3) h4⟩ :=
        congr_arg Q.triangles.get (Fin.ext rfl)
      have eQ2 : Q.triangles.get ⟨q₂-3, swap_idx P Q (q₂-3) hq2⟩ =
                 Q.triangles.get ⟨q₂-3, swap_idx P Q (q₂-3) h5⟩ :=
        congr_arg Q.triangles.get (Fin.ext rfl)
      rcases hmem with h|h|h|h
      · exact Or.inl  (eP2 ▸ eP1 ▸ h)
      · exact Or.inr (Or.inl  (eP1 ▸ eP2 ▸ h))
      · exact Or.inr (Or.inr (Or.inl  (eQ2 ▸ eQ1 ▸ h)))
      · exact Or.inr (Or.inr (Or.inr  (eQ1 ▸ eQ2 ▸ h))))
  else isFalse fun ⟨_, _, _, _, h, _⟩ => h5 h
  else isFalse fun ⟨_, _, _, h, _, _⟩ => h4 h
  else isFalse fun ⟨_, _, h, _, _, _⟩ => h3 h
  else isFalse fun ⟨_, h, _, _, _, _⟩ => h2 h
  else isFalse fun ⟨h, _, _, _, _, _⟩ => h1 h

/-- The discord graph G_R: vertices are discords, edges are welded pairs. -/
def GR_connected {n : ℕ} (P Q : Pedigree n) : Prop :=
  let D := discords P Q
  ∀ q₁ ∈ D, ∀ q₂ ∈ D,
    ∃ path : List ℕ, path.head? = some q₁ ∧ path.getLast? = some q₂ ∧
      path.IsChain (welded P Q) ∧ ∀ v ∈ path, v ∈ D

-- ============================================================================
-- SECTION 2: SWAP CONSTRUCTION
-- ============================================================================
-- Given component C ⊆ D of G_R, we swap P and Q's triples at C-layers.

-- Helper: P and Q agree at any layer l ≥ 3 outside discords (covers layer 3 via h_first).
private lemma agree_at_non_discord {n : ℕ} (P Q : Pedigree n) (l : ℕ)
    (hl3 : 3 ≤ l) (hln : l ≤ n) (h : l ∉ discords P Q) :
    edge_at P l = edge_at Q l := by
  by_cases hl4 : 4 ≤ l
  · exact not_discord_agree P Q l hl4 hln h
  · have hl3v : l = 3 := by omega
    subst hl3v
    have hlen  : 0 < P.triangles.length := by rw [P.h_length]; have := P.h_n; omega
    have hlenQ : 0 < Q.triangles.length := by rw [Q.h_length, ← P.h_length]; exact hlen
    have hhead : ∀ (ls : List Triple) (hl : 0 < ls.length),
        ls.head? = some (ls.get ⟨0, hl⟩) := fun ls hl => by
      match ls, hl with | _ :: _, _ => rfl
    have hfP : P.triangles.get ⟨0, hlen⟩ = (1, 2, 3) := by
      have hf := P.h_first; rw [hhead _ hlen] at hf; exact Option.some.inj hf
    have hfQ : Q.triangles.get ⟨0, hlenQ⟩ = (1, 2, 3) := by
      have hf := Q.h_first; rw [hhead _ hlenQ] at hf; exact Option.some.inj hf
    simp only [edge_at]
    rw [show (3:ℕ) - 3 = 0 from rfl, dif_pos hlen, dif_pos hlenQ, hfP, hfQ]

/-- Swap P's triples at layers in C with Q's triples.
    Constructs a valid Pedigree n; h_first and h_distinct require
    the generator/component property of C (left as sorry). -/
noncomputable def swap_pedigree {n : ℕ} (P Q : Pedigree n) (C : Finset ℕ)
    (hC_sub  : C ⊆ discords P Q)
    (hC_comp : ∀ q ∈ C, ∀ q', welded P Q q q' → q' ∈ C) : Pedigree n where
  triangles := List.ofFn (fun ⟨i, hi⟩ =>
      if (i : ℕ) + 3 ∈ C
      then Q.triangles.get ⟨i, swap_idx P Q i hi⟩
      else P.triangles.get ⟨i, hi⟩)
  h_n := P.h_n
  h_length := by simp [List.length_ofFn, P.h_length]
  h_first := by
    have hn    : 3 ≤ n                  := P.h_n
    have hlen  : 0 < P.triangles.length := by rw [P.h_length]; omega
    have hlenQ : 0 < Q.triangles.length := by rw [Q.h_length, ← P.h_length]; exact hlen
    -- head? of nonempty list = some (get ⟨0, _⟩) — definitional for cons
    have hhead : ∀ (l : List Triple) (hl : 0 < l.length),
        l.head? = some (l.get ⟨0, hl⟩) := fun l hl => by
      match l, hl with | _ :: _, _ => rfl
    -- Extract (1,2,3) from P and Q via hhead + h_first, avoiding cases on triangles
    have hfP : P.triangles.get ⟨0, hlen⟩ = (1, 2, 3) := by
      have hf := P.h_first; rw [hhead P.triangles hlen] at hf; exact Option.some.inj hf
    have hfQ : Q.triangles.get ⟨0, hlenQ⟩ = (1, 2, 3) := by
      have hf := Q.h_first; rw [hhead Q.triangles hlenQ] at hf; exact Option.some.inj hf
    -- Length of the ofFn list
    have hlen' : 0 < (List.ofFn (fun ⟨i, hi⟩ =>
        if (i : ℕ) + 3 ∈ C
        then Q.triangles.get ⟨i, swap_idx P Q i hi⟩
        else P.triangles.get ⟨i, hi⟩)).length := by
      simp only [List.length_ofFn, P.h_length]; omega
    rw [hhead _ hlen', List.get_ofFn]
    simp only [Fin.val_cast]
    congr 1
    split_ifs with hC
    · exact (congr_arg Q.triangles.get (Fin.ext rfl)).trans hfQ
    · exact (congr_arg P.triangles.get (Fin.ext rfl)).trans hfP
  h_layers := by
    intro i hi
    -- Convert: hi : i < (List.ofFn ...).length = P.triangles.length
    have hi' : i < P.triangles.length := by
      simp only [List.length_ofFn] at hi; exact hi
    simp only [List.get_ofFn, Fin.val_cast]
    split_ifs with hC
    · have := Q.h_layers i (swap_idx P Q i hi')
      simp only [Triple.k] at this ⊢; omega
    · have := P.h_layers i hi'
      simp only [Triple.k] at this ⊢; omega
  h_generators := by
    intro i hpos hi
    have hi' : i < P.triangles.length := by simp only [List.length_ofFn] at hi; exact hi
    simp only [List.get_ofFn, Fin.val_cast]
    split_ifs with hCi
    · -- i+3 ∈ C: triple is Q's triple at i+3
      obtain ⟨j, hjlt, hgen⟩ := Q.h_generators i hpos (swap_idx P Q i hi')
      have hj' : j < P.triangles.length := Nat.lt_trans hjlt hi'
      have hj4 : j + 3 ≤ n := by have := P.h_length; have := P.h_n; omega
      refine ⟨j, hjlt, ?_⟩
      by_cases hCj : j + 3 ∈ C
      · -- j+3 ∈ C: swap uses Q's triple = the generator ✓
        simp only [if_pos hCj]
        exact (congr_arg Q.triangles.get (Fin.ext rfl)).symm ▸ hgen
      · -- j+3 ∉ C: swap uses P's triple
        simp only [if_neg hCj]
        by_cases hj_disc : j + 3 ∈ discords P Q
        · -- j+3 ∈ D, j+3 ∉ C: welded P Q (i+3) (j+3) via Q-forward → j+3 ∈ C ✓
          exfalso; apply hCj
          apply hC_comp (i+3) hCi (j+3)
          have hq1 : i+3-3 < P.triangles.length := by have := P.h_length; have := P.h_n; omega
          have hq2 : j+3-3 < P.triangles.length := by have := P.h_length; have := P.h_n; omega
          refine ⟨hC_sub hCi, hj_disc, by omega, hq1, hq2,
                  Or.inr (Or.inr (Or.inl ?_))⟩
          simpa [show i+3-3=i from by omega, show j+3-3=j from by omega] using hgen
        · -- j+3 ∉ D: P and Q agree at j+3, so P's triple = Q's triple = generator ✓
          have hjP : j+3-3 < P.triangles.length := by omega
          have hjQ : j+3-3 < Q.triangles.length := by rw [Q.h_length, ← P.h_length]; omega
          have hPQ : P.triangles.get ⟨j, hj'⟩ = Q.triangles.get ⟨j, swap_idx P Q j hj'⟩ :=
            (congr_arg P.triangles.get (Fin.ext (Nat.add_sub_cancel_right j 3))).symm.trans
            ((same_edge_same_triple P Q (j+3) (by omega) hj4 hjP hjQ
              (agree_at_non_discord P Q (j+3) (by omega) hj4 hj_disc)).trans
             (congr_arg Q.triangles.get (Fin.ext (Nat.add_sub_cancel_right j 3))))
          rw [hPQ]; exact (congr_arg Q.triangles.get (Fin.ext rfl)).symm ▸ hgen
    · -- i+3 ∉ C: triple is P's triple at i+3
      by_cases hi_disc : i + 3 ∈ discords P Q
      · -- i+3 ∈ D: use P.h_generators; component argument available
        obtain ⟨j, hjlt, hgen⟩ := P.h_generators i hpos hi'
        have hj' : j < P.triangles.length := Nat.lt_trans hjlt hi'
        have hj4 : j + 3 ≤ n := by have := P.h_length; have := P.h_n; omega
        refine ⟨j, hjlt, ?_⟩
        by_cases hCj : j + 3 ∈ C
        · simp only [if_pos hCj]
          by_cases hj_disc : j + 3 ∈ discords P Q
          · -- j+3 ∈ D ∩ C, i+3 ∈ D: welded P Q (j+3) (i+3) via P-backward → i+3 ∈ C ✓
            exfalso; apply hCi
            apply hC_comp (j+3) hCj (i+3)
            have hq1 : j+3-3 < P.triangles.length := by have := P.h_length; have := P.h_n; omega
            have hq2 : i+3-3 < P.triangles.length := by have := P.h_length; have := P.h_n; omega
            refine ⟨hj_disc, hi_disc, by omega, hq1, hq2, Or.inr (Or.inl ?_)⟩
            simpa [show j+3-3=j from by omega, show i+3-3=i from by omega] using hgen
          · -- j+3 ∉ D: Q's triple = P's triple = generator ✓
            have hjP : j+3-3 < P.triangles.length := by omega
            have hjQ : j+3-3 < Q.triangles.length := by rw [Q.h_length, ← P.h_length]; omega
            have hPQ : P.triangles.get ⟨j, hj'⟩ = Q.triangles.get ⟨j, swap_idx P Q j hj'⟩ :=
              (congr_arg P.triangles.get (Fin.ext (Nat.add_sub_cancel_right j 3))).symm.trans
              ((same_edge_same_triple P Q (j+3) (by omega) hj4 hjP hjQ
                (agree_at_non_discord P Q (j+3) (by omega) hj4 hj_disc)).trans
               (congr_arg Q.triangles.get (Fin.ext (Nat.add_sub_cancel_right j 3))))
            rw [← hPQ]; exact hgen
        · simp only [if_neg hCj]; exact hgen
      · -- i+3 ∉ D: P.get ⟨i,_⟩ = Q.get ⟨i,_⟩; use Q.h_generators
        have hi4n : i + 3 ≤ n := by have := P.h_length; have := P.h_n; omega
        have hiPQ : P.triangles.get ⟨i, hi'⟩ = Q.triangles.get ⟨i, swap_idx P Q i hi'⟩ := by
          have hiP : i+3-3 < P.triangles.length := by omega
          have hiQ : i+3-3 < Q.triangles.length := by rw [Q.h_length, ← P.h_length]; omega
          exact (congr_arg P.triangles.get (Fin.ext (Nat.add_sub_cancel_right i 3))).symm.trans
            ((same_edge_same_triple P Q (i+3) (by omega) hi4n hiP hiQ
              (agree_at_non_discord P Q (i+3) (by omega) hi4n hi_disc)).trans
             (congr_arg Q.triangles.get (Fin.ext (Nat.add_sub_cancel_right i 3))))
        obtain ⟨k, hklt, hgenQ⟩ := Q.h_generators i hpos (swap_idx P Q i hi')
        have hk' : k < P.triangles.length :=
          swap_idx Q P k (Nat.lt_trans hklt (swap_idx P Q i hi'))
        have hk4n : k + 3 ≤ n := by have := P.h_length; have := P.h_n; omega
        -- helper facts for generators_layer
        have hQi_del := Q.h_in_delta i (swap_idx P Q i hi')
        have hQi_i1 := mem_Delta_i1 hQi_del
        have hQi_ij := mem_Delta_ij hQi_del
        refine ⟨k, hklt, ?_⟩
        by_cases hCk : k + 3 ∈ C
        · -- k+3 ∈ C: swap uses Q.get ⟨k,_⟩ = generator ✓
          simp only [if_pos hCk]
          rw [hiPQ]; exact (congr_arg Q.triangles.get (Fin.ext rfl)).symm ▸ hgenQ
        · simp only [if_neg hCk]
          by_cases hk_disc : k + 3 ∈ discords P Q
          · -- k+3 ∈ D, k+3 ∉ C, i+3 ∉ D:
            -- generators_layer shows generator layer = Q.get ⟨i,_⟩.j, uniquely.
            -- P.h_generators gives a generator at the SAME position k.
            -- The swap uses P.get ⟨k,_⟩ which is that generator. ✓
            obtain ⟨j', hj'lt, hgenP⟩ := P.h_generators i hpos hi'
            -- j' = k: both P and Q generators of Q.get ⟨i,_⟩ have k-value = Q.get ⟨i,_⟩.j
            have hk4 : k + 3 ≥ 4 := ((mem_discords_iff P Q (k+3)).mp hk_disc).1
            have hQk_val : (Q.triangles.get ⟨k, swap_idx P Q k hk'⟩).k = k + 3 := by
              have := Q.h_layers k (swap_idx P Q k hk'); simp [Triple.k] at this ⊢; omega
            have hQlayer : k + 3 = (Q.triangles.get ⟨i, swap_idx P Q i hi'⟩).j :=
              hQk_val ▸ generators_layer hQi_i1 hQi_ij hgenQ (by omega)
            -- Convert hgenP to be about Q.get ⟨i,_⟩ since P.get ⟨i,_⟩ = Q.get ⟨i,_⟩
            have hgenP' : P.triangles.get ⟨j', Nat.lt_trans hj'lt hi'⟩ ∈
                generators (Q.triangles.get ⟨i, swap_idx P Q i hi'⟩) := by
              rwa [← hiPQ, ← congr_arg generators (congr_arg P.triangles.get (Fin.ext rfl))]
            have hPj_val : (P.triangles.get ⟨j', Nat.lt_trans hj'lt hi'⟩).k = j' + 3 := by
              have := P.h_layers j' (Nat.lt_trans hj'lt hi'); simp [Triple.k] at this ⊢; omega
            have hj'_eq_k : j' = k := by
              have hPmem := mem_generators_Delta hQi_i1 hQi_ij hgenP'
              have htj : (Q.triangles.get ⟨i, swap_idx P Q i hi'⟩).j > 3 := by linarith
              rw [if_pos htj] at hPmem
              linarith [mem_Delta_k hPmem]
            -- goal: P.get ⟨k,_⟩ ∈ generators(P.get ⟨i,_⟩)
            have heq : P.triangles.get ⟨j', Nat.lt_trans hj'lt hi'⟩ =
                       P.triangles.get ⟨k, hk'⟩ :=
              congr_arg P.triangles.get (Fin.ext (by omega))
            rwa [heq] at hgenP
          · -- k+3 ∉ D: P.get ⟨k,_⟩ = Q.get ⟨k,_⟩ = generator ✓
            have hkP : k+3-3 < P.triangles.length := by omega
            have hkQ : k+3-3 < Q.triangles.length := by rw [Q.h_length, ← P.h_length]; omega
            have hkPQ : P.triangles.get ⟨k, hk'⟩ = Q.triangles.get ⟨k, swap_idx P Q k hk'⟩ :=
              (congr_arg P.triangles.get (Fin.ext (Nat.add_sub_cancel_right k 3))).symm.trans
              ((same_edge_same_triple P Q (k+3) (by omega) hk4n hkP hkQ
                (agree_at_non_discord P Q (k+3) (by omega) hk4n hk_disc)).trans
               (congr_arg Q.triangles.get (Fin.ext (Nat.add_sub_cancel_right k 3))))
            have : P.triangles.get ⟨k, hk'⟩ ∈ generators (P.triangles.get ⟨i, hi'⟩) := by
              rw [hiPQ, hkPQ]; exact (congr_arg Q.triangles.get (Fin.ext rfl)).symm ▸ hgenQ
            exact this
  h_distinct := by
    -- [SP-distinct] Both-from-P and both-from-Q cases are immediate.
    -- Mixed cases (one from Q, one from P at different positions) require
    -- C being a G_R component to exclude same-edge conflicts.
    intro i j hi hj hipos hjpos hij
    have hi' : i < P.triangles.length := by simp only [List.length_ofFn] at hi; exact hi
    have hj' : j < P.triangles.length := by simp only [List.length_ofFn] at hj; exact hj
    simp only [List.get_ofFn, Fin.val_cast]
    split_ifs with hCi hCj
    · -- Both from Q
      exact Q.h_distinct i j (swap_idx P Q i hi') (swap_idx P Q j hj') hipos hjpos hij
    · -- i from Q, j from P — mixed case
      sorry -- [SP-distinct-mixed] requires component property
    · -- i from P, j from Q — mixed case (symmetric)
      sorry -- [SP-distinct-mixed] requires component property
    · -- Both from P
      exact P.h_distinct i j hi' hj' hipos hjpos hij
  h_in_delta := by
    intro i hi
    have hi' : i < P.triangles.length := by simp only [List.length_ofFn] at hi; exact hi
    simp only [List.get_ofFn, Fin.val_cast]
    split_ifs with hC
    · exact Q.h_in_delta i (swap_idx P Q i hi')
    · exact P.h_in_delta i hi'

-- ============================================================================
-- SECTION 3: CONNECTED → ADJACENT (Theorem 4.18)
-- ============================================================================

theorem adjacent_if_GR_connected {n : ℕ} (P Q : Pedigree n)
    (hconn : GR_connected P Q) :
    AdjacentInPolytope P Q := by
  intro S μ h_sum h_pos h_mid
  suffices h_either : ∀ R ∈ S, R = P ∨ R = Q by
    have hP_in : P ∈ S := by
      by_contra hP_not
      have hall_Q : ∀ Z ∈ S, Z = Q :=
        fun Z hZ => (h_either Z hZ).resolve_left fun h => hP_not (h ▸ hZ)
      sorry
    have hQ_in : Q ∈ S := by
      by_contra hQ_not
      have hall_P : ∀ Z ∈ S, Z = P :=
        fun Z hZ => (h_either Z hZ).resolve_right fun h => hQ_not (h ▸ hZ)
      sorry
    ext x; simp
    exact ⟨fun hx => (h_either x hx).imp id id,
           fun hx => hx.elim (· ▸ hP_in) (· ▸ hQ_in)⟩
  intro R hR
  by_contra hboth
  push_neg at hboth
  obtain ⟨hRP, hRQ⟩ := hboth
  -- R must pick tP(q) or tQ(q) at each discord q.
  -- G_R connectivity forces a consistent choice at all discords.
  sorry

-- ============================================================================
-- SECTION 4: DISCONNECTED → NON-ADJACENT (Theorem 4.19)
-- ============================================================================

theorem nonadjacent_if_GR_disconnected {n : ℕ} (P Q : Pedigree n)
    (hdisconn : ¬ GR_connected P Q)
    (hne : P ≠ Q) :
    ¬ AdjacentInPolytope P Q := by
  intro h_adj
  -- Extract a proper component C ⊊ D.
  obtain ⟨C, hC_sub, hC_ne, hC_prop⟩ : ∃ C : Finset ℕ,
      C ⊆ discords P Q ∧ C.Nonempty ∧ C ≠ discords P Q := by
    simp [GR_connected] at hdisconn
    sorry
  -- Construct P' and Q' by swapping at C.
  -- hC_comp: C is closed under welding — needed for swap_pedigree's h_generators.
  -- [comp] This follows from C being a connected component; left as sorry pending component extraction.
  have hC_comp : ∀ q ∈ C, ∀ q', welded P Q q q' → q' ∈ C := by sorry
  have hC_sub_QP : C ⊆ discords Q P := by
    intro q hq
    rw [mem_discords_iff]
    have h := (mem_discords_iff P Q q).mp (hC_sub hq)
    exact ⟨h.1, h.2.1, Ne.symm h.2.2⟩
  have hC_comp_QP : ∀ q ∈ C, ∀ q', welded Q P q q' → q' ∈ C := by sorry
  let P' := swap_pedigree P Q C hC_sub hC_comp
  let Q' := swap_pedigree Q P C hC_sub_QP hC_comp_QP
  -- Pick the discord witness layer c ∈ C to separate P' from P and Q' from Q.
  obtain ⟨c, hcC⟩ := hC_ne
  have hc_discord : c ∈ discords P Q := hC_sub hcC
  have hc4 : 4 ≤ c := ((mem_discords_iff P Q c).mp hc_discord).1
  have hcn : c ≤ n := ((mem_discords_iff P Q c).mp hc_discord).2.1
  have hc_ne : edge_at P c ≠ edge_at Q c := ((mem_discords_iff P Q c).mp hc_discord).2.2
  -- P' ≠ P: at layer c, P' uses Q's triple which differs from P's.
  have hP'neP : P' ≠ P := by
    sorry
  -- Q' ≠ Q: by the same discord, Q' uses P's triple which differs from Q's.
  have hQ'neQ : Q' ≠ Q := by
    sorry
  -- Midpoint of P' and Q' equals midpoint of P and Q.
  have h_mid_eq : ∀ t : Triple, t.k ≤ n →
      (char_vec P t + char_vec Q t) / 2 =
      (char_vec P' t + char_vec Q' t) / 2 := by
    sorry
  -- Apply h_adj: the only convex witness for the midpoint is {P, Q}.
  -- But {P', Q'} is also a witness with P' ≠ P and Q' ≠ Q — contradiction.
  sorry

-- ============================================================================
-- SECTION 5: FULL CHARACTERISATION AND COMBINATORIAL POLYTOPE
-- ============================================================================

/-- P and Q are adjacent in conv(Pₙ) iff G_R(P,Q) is connected.
    Combined Theorems 4.18 and 4.19. -/
theorem pedigree_adjacency_iff_GR_connected {n : ℕ} (P Q : Pedigree n)
    (hne : P ≠ Q) :
    AdjacentInPolytope P Q ↔ GR_connected P Q :=
  ⟨fun h => by
    by_contra hd
    exact nonadjacent_if_GR_disconnected P Q hd hne h,
   adjacent_if_GR_connected P Q⟩

/-- conv(Pₙ) is a combinatorial polytope:
    adjacency is determined entirely by the pedigree structure. -/
theorem pedigree_polytope_combinatorial {n : ℕ} :
    ∀ (P Q : Pedigree n), P ≠ Q →
    (AdjacentInPolytope P Q ↔ GR_connected P Q) :=
  fun P Q hne => pedigree_adjacency_iff_GR_connected P Q hne

end MembershipProject.Core
